### ISSUE TITLE
Auth token not found

### ISSUE THREAD

**Issue by amorabito** [Bernstern/MagicRSVP#1]
Hello friend, I appreciate your repository and outlining these APIs, very helpful.

I was testing this API from Postman.
https://disneyland.disney.go.com/finder/api/v1/explorer-service/list-ancestor-entities/dlr/80008297;entityType=destination/{TARGET_DATE}/dining

Setting {TARGET_DATE} to 2022-08-26

I am seeing this response, how are you handling this? Thanks again!

`
{
  “typeId”: “UNAUTHORIZED”,
  “message”: “Auth token not found”
}
`

**Comment by amorabito** [comment]
I think you can use this to retrieve Auth cookies in response headers. In postman calling this first allows original API to Authenticate fine.


```
import requests

url = "https://disneyland.disney.go.com/finder/api/v1/authz/public"

payload="{}"
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

**Comment by Bernstern** [comment]
Hi @amorabito thank you for finding this! I will try to merge this in this weekend, I am going to try to make the main script a little more flexible and not depend on AWS to function.
